spring:
  datasource:
    platform: h2 
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:zoo-monolith-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  
  h2:
   console:
     enabled: true
     path: /console
 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true  
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update

 